"""aggiunge nome alle integrazioni

Revision ID: 1b39bfa8b911
Revises: ce3b44de8000
Create Date: 2026-08-16 22:00:34.813017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b39bfa8b911'
down_revision: Union[str, None] = 'ce3b44de8000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Le integrazioni create prima di questa colonna restavano senza nome
    # (l'API le mostrava già come "provider #id" via un ripiego lato codice,
    # ma qui lo scriviamo davvero nella riga così anche chi legge il dato
    # direttamente, non solo tramite l'endpoint, vede qualcosa di leggibile).
    op.execute("UPDATE integrations SET name = provider || ' #' || id WHERE name IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'name')
    # ### end Alembic commands ###
