"""aggiunge azioni_pendenti e azione_template

Revision ID: 2d65904699b7
Revises: f414e5fcdc5d
Create Date: 2026-08-25 18:42:03.585579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d65904699b7'
down_revision: Union[str, None] = 'f414e5fcdc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azioni_pendenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('origine', sa.String(length=255), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_azioni_pendenti_id'), 'azioni_pendenti', ['id'], unique=False)
    # server_default: c'è già almeno una riga esistente in alert_rules, una
    # colonna NOT NULL senza default fallirebbe su quelle righe.
    op.add_column('alert_rules', sa.Column('azione_template', sa.Text(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'azione_template')
    op.drop_index(op.f('ix_azioni_pendenti_id'), table_name='azioni_pendenti')
    op.drop_table('azioni_pendenti')
    # ### end Alembic commands ###
