"""aggiunge notifiche_inviate

Revision ID: 8fd9dc7ef8e0
Revises: 1b39bfa8b911
Create Date: 2026-08-18 18:00:55.439784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd9dc7ef8e0'
down_revision: Union[str, None] = '1b39bfa8b911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifiche_inviate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('chiave', sa.String(length=255), nullable=False),
    sa.Column('inviata_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'chiave', name='uq_notifica_org_chiave')
    )
    op.create_index(op.f('ix_notifiche_inviate_id'), 'notifiche_inviate', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifiche_inviate_id'), table_name='notifiche_inviate')
    op.drop_table('notifiche_inviate')
    # ### end Alembic commands ###
