"""aggiunge memberships

Revision ID: f414e5fcdc5d
Revises: 8fd9dc7ef8e0
Create Date: 2026-08-25 18:23:40.486009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f414e5fcdc5d'
down_revision: Union[str, None] = '8fd9dc7ef8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: ogni utente esistente deve continuare ad avere accesso alla
    # propria azienda attuale — senza questo, la tabella nuova esisterebbe ma
    # nessuno vi comparirebbe, e la prima chiamata a /auth/my-organizations
    # tornerebbe vuota anche per chi ha già un'azienda vera.
    op.execute(
        "INSERT INTO memberships (user_id, organization_id, created_at) "
        "SELECT id, organization_id, created_at FROM users"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_table('memberships')
    # ### end Alembic commands ###
